# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Beyond Basics: Mastering Advanced Python — a book to learn expert aspects of Python language"
author: Jakub Walczak, PhD
logo: figs/logo_noname.svg
copyright: "2025"
language: "en"
exclude_patterns:
  - _build

launch_buttons:
  notebook_interface: "classic"
  binderhub_url: ""

sphinx:
  config:
    language: en
    bibtex_reference_style: author_year
    bibtex_bibfiles: 
      - ./references.bib
    html_context:
      default_mode: light
      

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  timeout: 10000
  execute_notebooks: cache

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/HappyRavenLabs/python-beyond-basics # Online location of your book

# Add GitHub buttons to your book
html:
  favicon: "figs/favicon.ico"
  use_multitoc_numbering: true
  home_page_in_navbar: true
  use_issues_button: true
  use_repository_button: false
