name: Deploy Jupyter Book

on:
  push:
    tags:
      - 'v*' 

permissions:
  contents: write      

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install .
          pip install ghp-import

      - name: Build the book
        run: jupyter-book build .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
